name: Commit Checks

on:
  push:
    branches:
      - '**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Enable Corepack and Use pnpm
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Svelte Check
        run: pnpm check

      - name: Run Lint
        run: pnpm lint

      - name: Run Unit Tests
        run: pnpm test:unit
